# Generated by Django 5.1.4 on 2024-12-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cliente_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='profissao',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='0', max_length=14),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
